name: Continuos Deployment workflow

on:
  push:
    branches:
      - main
env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  IMAGE_NAME: registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web
  APP_NAME: ${{ secrets.HEROKU_APP_NAME }}:${{ github.run_id }}

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install heroku and login
        # Login using HEROKU_API_KEY env variable
        run: |
          curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
          heroku container:login
      - name: Build docker image
        run: docker build -t ${{ env.APP_NAME }} .
      - name: Deploy docker image
        run: |
          docker tag ${{ env.APP_NAME }} ${{env.IMAGE_NAME}}
          docker push ${{env.IMAGE_NAME}}
      - name: Release
        run: heroku container:release web -a ${{ secrets.HEROKU_APP_NAME }}
